<?php
$this->headTitle('View Product');

$this->mainMenu()->setActiveItemId('users');

?>

<?//= $this->flashMessenger()->render('error', ['alert', 'alert-warning']); ?>
<?//= $this->flashMessenger()->render('success', ['alert', 'alert-success']); ?>
<?//= $this->flashMessenger()->render('info', ['alert', 'alert-info']); ?>

<h1>View User</h1>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($product->getId()) ?></th>
            </tr>
            <tr>
                <th>Namel:</th>
                <td><?= $this->escapeHtml($product->getName()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($product->getCreated()) ?></th>
            </tr>

        </table>
    </div>
</div>