<?php

//$this->headTitle('productRepos');

//$this->mainMenu()->setActiveItemId('productRepo');
?>

<h1>Manage productRepos</h1>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('repo', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New productRepo
    </a>
</p>

<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>
    <?php foreach($productRepos as $productRepo): ?>
        <tr>
            <td><?= $this->escapeHtml($productRepo->getId()); ?></td>
            <td><?= $this->escapeHtml($productRepo->getName()); ?></a>
            </td>
            <td><?= $this->escapeHtml($productRepo->getCreated()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('repo',
                    ['action' => 'edit', 'id' => $productRepo->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil"></span> Edit
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

