<?php
$this->headTitle('Welcome');

$this->mainMenu()->setActiveItemId('home');

/*$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home')
            ]);*/
?>

<h1>Welcome</h1>



<p>
    Click the <em>Sign in</em> button at the top right. To sign in, use the 
    following credentials:
    <ul>
        <li>telefon: <em>5555</em></li>
        <li>Password: <em>Moje1234</em></li>
    </ul>    
</p>



