<?php
$this->headTitle('ProductRepos');
$this->mainMenu()->setActiveItemId('ProductRepo');
?>

<h1>Manage ProductRepos</h1>

<p>
    <a class="btn btn-default" href="
    <?= $this->url('ProductRepo', ['action' => 'add']); ?>">
        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New ProductRepo
    </a>
</p>

<table class="table table-striped">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>
    <?php foreach($ProductRepos as $ProductRepo): ?>
        <tr>
            <td><?= $this->escapeHtml($ProductRepo->getId()); ?></td>
            <td><?= $this->escapeHtml($ProductRepo->getName()); ?></a>
            </td>
            <td><?= $this->escapeHtml($ProductRepo->getCreated()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('ProductRepo',
                    ['action' => 'edit', 'id' => $ProductRepo->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil"></span> Edit
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

